"""exception.py - custom exceptions"""


class ScarceDataError(ValueError):
    pass
